### ISSUE TITLE
Embed it in an arbitrary c++ app

### ISSUE THREAD

**Issue by dio** [rianhunter/wasmjit#10]
I've been playing with https://github.com/rossberg/wasm-c-api and it is obvious for me how the "interop" works e.g. calling imports' functions (https://github.com/rossberg/wasm-c-api/blob/master/example/hello.cc). To enable the same experience and probably the ergonomics of wasm-c-api but with wasmjit, what should we prepare and build at first?

Thanks!

**Comment by rianhunter** [comment]
Unfortunately during the fury of writing this, I neglected to make the headers C++ compatible. I'll do this tomorrow. In the mean time, check out main.c / high_level.h / high_level.c to see how to interact with wasmjit. I follow the browser API semantics as much as possible so it shouldn't be difficult to adapt to wasm-c-api.

**Comment by dio** [comment]
@rianhunter thanks! will take a look.
