### ISSUE TITLE
wasmjit not responding 

### ISSUE THREAD

**Issue by zhuguoliang** [rianhunter/wasmjit#11]
![image](https://user-images.githubusercontent.com/9863649/46998728-ff45f400-d155-11e8-98a0-0aff3d53f302.png)
I am working on ubuntu 16.04 with kernel 4.17.0, everything including emsdk are successfully installed. However the wasm version of selfpipe hangs with no output.

**Comment by rianhunter** [comment]
Thanks for the report

**Comment by rianhunter** [comment]
I suspect the null point dereference is due to the NX protected page exception. What version kernel are you running?

**Comment by rianhunter** [comment]
Hmm just tried to reproduce this on my kernel and it ran successfully: `uname -a`: `Linux test 4.17.17 #2 SMP Sat Sep 1 19:02:29 PDT 2018 x86_64 GNU/Linux`
