### ISSUE TITLE
example fails on macOS 10.13

### ISSUE THREAD

**Issue by lionkov** [rianhunter/wasmjit#12]
wasmjit$ emcc -O3 -o selfpipe.js src/wasmjit_examples/selfpipe.c
wasmjit$ ./wasmjit selfpipe.wasm
failed to instantiate module: couldn't find func import: env.c [I32,I32,] -> [I32,]

**Comment by rianhunter** [comment]
Emscripten now minifies JS<->wasm export names on `-O3`, use `-O2` instead. Also pull the latest version of wasmjit.
