### ISSUE TITLE
Q: hardware platforms

### ISSUE THREAD

**Issue by grahamehorner** [rianhunter/wasmjit#17]
I would be interested in working along side you on this project with a view to looking at the hardware platforms that it could target and the performance.

Idea is that ahead-of-time compiled such as #mono-wasm-mono could run at almost native speed, and therefor possible support applications/components written using .NET core c# and deployed across the full range of devices including #IoT type devices like the ESP32 etc. with little/no change.

**Comment by rianhunter** [comment]
I'm not sure what the question is here but glad you're excited about the project.

As for the use-case you mentioned, why not add an ESP32 backend to mono? It would perform strictly better than a c#->wasm->esp32 path.

**Comment by rianhunter** [comment]
Everything is written to be minimal, but there is liberal of use of malloc() which may not be appropriate for an embedded platform. Performance is reasonably optimal, since wasm translates well to machine code.
