### ISSUE TITLE
README.md - typo?

### ISSUE THREAD

**Issue by evandrix** [rianhunter/wasmjit#2]
In your README.md, it is written `./wasmjit selfpipe.wasm`
Running that, I get the error message "Couldn't get static bump!"
Do you mean to write `./wasmjit selfpipe.js`?

**Comment by rianhunter** [comment]
No, `emcc` expects the a js extension argument to the `-o` option. This will output both a selfpipe.wasm file and a selfpipe.js file. `wasmjit` accepts a the wasm file as the argument. To retrieve the static bump, it reads the js file, but for some reason it's unable to read it here.

Are both the selfpipe.js and selfpipe.wasm files in the same directory? Can you post your selfpipe.js file here?

**Comment by rianhunter** [comment]
closing after inactivity
