### ISSUE TITLE
Couldn't get static bump!

### ISSUE THREAD

**Issue by vshymanskyy** [rianhunter/wasmjit#21]
Getting `Couldn't get static bump!` when running the selfpipe.wasm example.
Just installed the version from master, and a recent emscripten:
```
PATH += /opt/emsdk/clang/e1.38.29_64bit
PATH += /opt/emsdk/node/8.9.1_64bit/bin
PATH += /opt/emsdk/emscripten/1.38.29
```

**Comment by rianhunter** [comment]
Two possible reasons, 1) selfpipe.js should be in the same directory as selfpipe.wasm, 2) Emscripten has changed WASM ABI's, try using version 1.38.22, see #19 (this will be fixed soon)

**Comment by vshymanskyy** [comment]
yes I see the selfpipe.js is the same directory

**Comment by vshymanskyy** [comment]
Works now, after the latest updates. Thanks!
