### ISSUE TITLE
How to utilize multi core CPU

### ISSUE THREAD

**Issue by nidin** [rianhunter/wasmjit#3]
I was wondering how to do multi threading with wasmjit. At present Wasm support worker based multi threading and shared memory. Is it possible to instantiate another wasm module from a wasmjit module and communicate each other?
Also any plan for GPU bindings ?

**Comment by rianhunter** [comment]
wasm doesn't support multi-threading yet. wasmjit supports running different instances of wasmjit in multiple threads, but you need to provide a communication mechanism for your different instances to communicate. this is not currently provided by the wasmjit runtime, but you can roll it yourself.

**Comment by nidin** [comment]
Upcoming wasm supports worker based threading
https://www.chromestatus.com/feature/5724132452859904

Is it possible that two wasmjit modules share a single memory?

**Comment by rianhunter** [comment]
Yes, though without atomic instructions, there would be inherent data races.

**Comment by nidin** [comment]
Atomic instructions are already in spec.
https://github.com/WebAssembly/threads/blob/master/proposals/threads/Overview.md#atomic-memory-accesses

**Comment by rianhunter** [comment]
That's still in the proposal phase. Once they have been approved I will prioritize their inclusion in wasmjit. For now, there is risk of redundant work and there are more important priorities. Feel free to open a PR.
