### ISSUE TITLE
Missing semi-colen in make -j wasmjit

### ISSUE THREAD

**Issue by msampathkumar** [rianhunter/wasmjit#4]
➜  wasmjit git:(master) make -j wasmjit
cc -c -o src/wasmjit/main.o src/wasmjit/main.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/vector.o src/wasmjit/vector.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/ast.o src/wasmjit/ast.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/parse.o src/wasmjit/parse.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/ast_dump.o src/wasmjit/ast_dump.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/compile.o src/wasmjit/compile.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/runtime.o src/wasmjit/runtime.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/util.o src/wasmjit/util.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/elf_relocatable.o src/wasmjit/elf_relocatable.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/dynamic_emscripten_runtime.o src/wasmjit/dynamic_emscripten_runtime.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/emscripten_runtime_sys_posix.o src/wasmjit/emscripten_runtime_sys_posix.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/instantiate.o src/wasmjit/instantiate.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/emscripten_runtime.o src/wasmjit/emscripten_runtime.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/high_level.o src/wasmjit/high_level.c -Isrc -g -Wall -Wextra -Werror
cc -c -o src/wasmjit/dynamic_runtime.o src/wasmjit/dynamic_runtime.c -Isrc -g -Wall -Wextra -Werror

src/wasmjit/emscripten_runtime.c:2283:55: error: expected ';' after expression
                base = wasmjit_emscripten_get_base_address(funcinst)
                                                                    ^
                                                                    ;
1 error generated.
make: *** [src/wasmjit/emscripten_runtime.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by msampathkumar** [comment]
Pull request is at - [https://github.com/rianhunter/wasmjit/pull/5](https://github.com/rianhunter/wasmjit/pull/5) Please check it !

**Comment by rianhunter** [comment]
Fixed in 6227b64668a6465221fef2ee9d92302b8d5bfa9f
